In [4]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
df = pd.read_csv("data.txt", sep = " ")

In [5]:
df.head()

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,...,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4006,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4001,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4016,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0

In [6]:
#.找出 与 is_trade 相关性最高的前3个字段，并理解下这些高相关性字段代表的含义   【容易】


df.corr()["is_trade"].sort_values(ascending = False)

is_trade                     1.000000
item_sales_level             0.037358
item_collected_level         0.013972
user_gender_id               0.008843
item_pv_level                0.006077
user_age_level               0.002628
user_star_level              0.002239
user_occupation_id           0.002026
user_id                      0.000255
item_id                     -0.000168
shop_star_level             -0.000735
shop_review_num_level       -0.000747
instance_id                 -0.002158
shop_id                     -0.003238
context_id                  -0.003459
item_brand_id               -0.005311
context_timestamp           -0.009274
context_page_id             -0.012313
item_city_id                -0.014622
shop_score_service          -0.015578
shop_score_delivery         -0.016239
shop_score_description      -0.016734
shop_review_positive_rate   -0.017355
item_price_level            -0.055895
Name: is_trade, dtype: float64

In [ ]:
#Answer: item_price_level            -0.055895 负相关
#        item_sales_level             0.037358 正相关
#        shop_review_positive_rate   -0.017355 负相关

In [ ]:
#新增一列，表示item_id最近三天的历史转化率  提示：先把context_timestamp 转换成 日期 【较难】

In [12]:
df["formatted_context_timestamp"] =df["context_timestamp"].apply(lambda x: datetime.fromtimestamp(x).date())

In [13]:
df.head()

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,...,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,formatted_context_timestamp
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,2018-09-17
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,2018-09-17
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,2018-09-17
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,2018-09-17
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0,2018-09-18

In [14]:
df["formatted_context_timestamp"].unique()

array([datetime.date(2018, 9, 17), datetime.date(2018, 9, 18),
       datetime.date(2018, 9, 20), datetime.date(2018, 9, 21),
       datetime.date(2018, 9, 19), datetime.date(2018, 9, 22),
       datetime.date(2018, 9, 23), datetime.date(2018, 9, 24)],
      dtype=object)